OUT_FILE = 'outputfile'
MESSAGE_MAX_WIDTH = 'out_width'

ENV_PREFIX = 'DEBUGBEE_'
ENV_OUTPUT_FILE = ENV_PREFIX + 'OUTPUT_FILE'
ENV_IDENTATION = ENV_PREFIX + 'IDENTATION'
ENV_CALLER_DEPTH = ENV_PREFIX + 'CALLER_DEPTH'
ENV_LIST_ARGUMENTS = ENV_PREFIX + 'LIST_ARGUMENTS'
ENV_OUT_WIDTH = ENV_PREFIX + 'OUT_WIDTH'
